### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by iva-5-middleware** [mattermost-community/mattermost-plugin-confluence#121]
Hey there,

we would really like to use the confluence integration, but I saw that the latest release is from 2022 and the last commit is also a few months old.

So I wonder if this plugin is still maintained.
And to what Mattermost and Confluence (Data Center) versions is it compatible at the moment? I saw `"min_server_version": "5.26.0"`, but what is the max_server_version at the moment?

Best regards!

**Comment by hanzei** [comment]
It's best to consider this project unmaintained. Still, I'm curious if you encounter any issues while deploying the plugin.

**Comment by iva-5-middleware** [comment]
That's too bad, thanks for your reply! I haven't deployed the plugin yet. At first, I wanted to make sure that this project is still actively maintained
